"""third commit

Revision ID: 5736d9de9938
Revises: fb5e967c5b5a
Create Date: 2023-08-29 20:14:27.177448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5736d9de9938'
down_revision: Union[str, None] = 'fb5e967c5b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('dueDate', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'project_id')
    op.drop_column('task', 'dueDate')
    # ### end Alembic commands ###
